[package]
name = "rust-chat-server"
version = "0.1.5"
authors = ["Mitchell <mitchellhardie1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
crossbeam = "0.7"
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
crossbeam-queue = "0.2"
parking_lot = "0.10"
dashmap = "3.11.4"
async-std = "1.6.2"
lazy_static = "1.4.0"
rayon = "1.3.1"
diesel = { version = "1.4.5", features = ["sqlite"] }
zeroize = "1.1.0"
cursive = { version = "0.15.0", default-features = false, features = ["crossterm-backend"]}
crossterm = "0.17.7"
log = "0.4"
clap = "3.0.0-beta.1"



[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
