name: Check and test server

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install protobuffer compiler
      run: sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@v4
    - name: check
      run: cargo check --verbose
    - name: test
      run: cargo test --verbose
